// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBedn-rAB12gyzaM0EIUypGolwHP29dho8',
    appId: '1:157640792419:web:776c6869e50b6cfc9c1b56',
    messagingSenderId: '157640792419',
    projectId: 'rainsafe-ffa15',
    authDomain: 'rainsafe-ffa15.firebaseapp.com',
    storageBucket: 'rainsafe-ffa15.firebasestorage.app',
    measurementId: 'G-GP5108CPF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVP5FUDPU88zyC03ec9ewgkgAOvYy9Sko',
    appId: '1:157640792419:android:332e6fa39f7c62669c1b56',
    messagingSenderId: '157640792419',
    projectId: 'rainsafe-ffa15',
    storageBucket: 'rainsafe-ffa15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABVLvsEt_ktT7ys5ghw41-2pzdfEeFTjE',
    appId: '1:157640792419:ios:8c233f723204b27f9c1b56',
    messagingSenderId: '157640792419',
    projectId: 'rainsafe-ffa15',
    storageBucket: 'rainsafe-ffa15.firebasestorage.app',
    iosBundleId: 'com.example.rainsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABVLvsEt_ktT7ys5ghw41-2pzdfEeFTjE',
    appId: '1:157640792419:ios:8c233f723204b27f9c1b56',
    messagingSenderId: '157640792419',
    projectId: 'rainsafe-ffa15',
    storageBucket: 'rainsafe-ffa15.firebasestorage.app',
    iosBundleId: 'com.example.rainsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBedn-rAB12gyzaM0EIUypGolwHP29dho8',
    appId: '1:157640792419:web:a4f0197a6280f8729c1b56',
    messagingSenderId: '157640792419',
    projectId: 'rainsafe-ffa15',
    authDomain: 'rainsafe-ffa15.firebaseapp.com',
    storageBucket: 'rainsafe-ffa15.firebasestorage.app',
    measurementId: 'G-W82FBKSRQ6',
  );
}
